In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
fake1 = pd.read_csv("../data/raw/fakenewsnet/BuzzFeed_fake_news_content.csv")
real1 = pd.read_csv("../data/raw/fakenewsnet/BuzzFeed_real_news_content.csv")

In [3]:
print(fake1.columns)
print(real1.columns)

Index(['id', 'title', 'text', 'url', 'top_img', 'authors', 'source',
       'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'],
      dtype='str')
Index(['id', 'title', 'text', 'url', 'top_img', 'authors', 'source',
       'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'],
      dtype='str')

In [4]:
fake1["text"] = fake1["title"].fillna('') + " " + fake1["text"].fillna('')

real1["text"] = real1["title"].fillna('') + " " + real1["text"].fillna('')

In [5]:
fake1["label"] = 1
real1["label"] = 0

In [6]:
fake1 = fake1[["text", "label"]]
real1 = real1[["text", "label"]]

In [7]:
df1 = pd.concat([fake1, real1])

In [8]:
df1.head()

                                                text  label
0  Proof The Mainstream Media Is Manipulating The...      1
1  Charity: Clinton Foundation Distributed “Water...      1
2  A Hillary Clinton Administration May be Entire...      1
3  Trump’s Latest Campaign Promise May Be His Mos...      1
4  Website is Down For Maintenance Website is Dow...      1

In [9]:
df1.isnull().sum()

text     0
label    0
dtype: int64

In [10]:
df1.dropna(inplace=True)

In [11]:
df1 = df1.sample(frac=1, random_state=42)

In [12]:
df1.head()

                                                 text  label
19  How Democrats are Going to Try to STEAL the El...      1
42  Tebow DISMANTLES national anthem protests in o...      1
63  Terrorist Attacks Will Likely Affect 2016 Pres...      0
7   Young Girl's Emotional Council Speech Laments ...      0
55  Obama weighs in on the debate Obama weighs in ...      0

In [13]:
df1.to_csv("../data/processed/fakenewsnet_cleaned.csv", index=False)

In [14]:
liar = pd.read_csv("../data/raw/liar/train.tsv", sep="\t", header=None)

In [15]:
liar.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,2635.json,false,Says the Annies List political group supports ...,abortion,dwayne-bohac,State representative,Texas,republican,0.0,1.0,0.0,0.0,0.0,a mailer
1,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
2,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
3,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
4,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN

In [16]:
liar.shape

(10240, 14)

In [17]:
liar.columns = [
    "id",
    "label",
    "statement",
    "subject",
    "speaker",
    "speaker_job",
    "state_info",
    "party_affiliation",
    "barely_true_counts",
    "false_counts",
    "half_true_counts",
    "mostly_true_counts",
    "pants_on_fire_counts",
    "context"
]

In [18]:
print(liar.columns)

Index(['id', 'label', 'statement', 'subject', 'speaker', 'speaker_job',
       'state_info', 'party_affiliation', 'barely_true_counts', 'false_counts',
       'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts',
       'context'],
      dtype='str')

In [19]:
liar = liar[["statement", "label"]]

In [20]:
liar.rename(columns={"statement": "text"}, inplace=True)

In [21]:
liar["label"].value_counts()

label
half-true      2114
false          1995
mostly-true    1962
true           1676
barely-true    1654
pants-fire      839
Name: count, dtype: int64

In [22]:
label_map = {
    "true": 0,
    "mostly-true": 0,
    "half-true": 0,
    "false": 1,
    "pants-fire": 1,
    "barely-true": 1
}

In [23]:
liar["label"] = liar["label"].map(label_map)

In [24]:
liar.head()

                                                text  label
0  Says the Annies List political group supports ...      1
1  When did the decline of coal start? It started...      0
2  Hillary Clinton agrees with John McCain "by vo...      0
3  Health care reform legislation is likely to ma...      1
4  The economic turnaround started at the end of ...      0

In [25]:
liar.isnull().sum()

text     0
label    0
dtype: int64

In [26]:
liar.dropna(inplace=True)

In [27]:
liar.drop_duplicates(subset=["text"], inplace=True)

In [28]:
liar = liar.sample(frac=1, random_state=42)

In [29]:
liar.head()

                                                   text  label
2887                  Countries bombed: Obama 7, Bush 4      0
4521  Says she couldn't take stimulus money because ...      1
7731  In the past decade, K-12 funding has grown six...      0
33    We cut business taxes so today 70 percent of o...      0
4932  A proposed mine in Wisconsin is about two-thir...      1

In [30]:
liar.to_csv("../data/processed/liar_cleaned.csv", index=False)

In [34]:
df3 = pd.read_csv(
    "../data/raw/dataset3/train.csv",
    engine="python",
    on_bad_lines="skip",
    quoting=3
)

In [35]:
df3.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;title;text;label
0;Palestinians switch off Christmas lights in B... West Bank (Reuters) - Palestinians switched off... where Christians believe Jesus was born             and another in Ramallah                            next to the burial site of former Palestinian ...  were plunged into darkness.  The Christmas tre...   said Fady Ghattas                                 Bethlehem s municipal media officer.  He said ...  Trump said he had decided to recognize Jerusal...   calling it an incendiary move in a volatile r...
1;China says Trump call with Taiwan president w... China’s Taiwan Affairs Office said on Saturday.... it said                                             in a statement released on the official Xinhua... nan                                                nan                                                nan                                                nan                                                nan                                                                                               NaN
4;THE MOST UNCOURAGEOUS PRESIDENT EVER Receives... he s the one who gave Iran the opportunity to h... he never took the blame but pointed at anyone a...  the boondoggle of Solendra and Obamacare He ne...  days after House Republicans won passage of a ...  and has avoided mention of his Republican succ...  even as President Donald Trump has criticized ...  named for a 1957 Pulitzer Prize-winning book b...  members of Congress                                 former Obama staffers and celebrities includi...
9;MACY’S GETS THE BOOT FROM LOYAL CUSTOMERS AFT... because we ve learned thousands of customers ar... Macy s has received complaints from approximate... 000 customers since ending its relationship wit...  including phone                                    Facebook and email. A Macy s spokesperson woul...   Our Facebook page is often times used by our ... nan                                                nan                                                                                               NaN
15;White House declines to say if Trump has mad... despite reports indicating that he would pull o... Spicer said: “When the president has a decision     he’ll make that announcement and he’ll make it...  Spicer said: “I obviously don’t know whether o...  but when he’s ready to make an announcement        he’ll make it clear.” ;1                          nan                                                nan                                                                                               NaN

In [36]:
print(df3.columns)

Index([';title;text;label'], dtype='str')

In [37]:
df3.iloc[:5]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;title;text;label
0;Palestinians switch off Christmas lights in B... West Bank (Reuters) - Palestinians switched off... where Christians believe Jesus was born             and another in Ramallah                            next to the burial site of former Palestinian ...  were plunged into darkness.  The Christmas tre...   said Fady Ghattas                                 Bethlehem s municipal media officer.  He said ...  Trump said he had decided to recognize Jerusal...   calling it an incendiary move in a volatile r...
1;China says Trump call with Taiwan president w... China’s Taiwan Affairs Office said on Saturday.... it said                                             in a statement released on the official Xinhua... nan                                                nan                                                nan                                                nan                                                nan                                                                                               NaN
4;THE MOST UNCOURAGEOUS PRESIDENT EVER Receives... he s the one who gave Iran the opportunity to h... he never took the blame but pointed at anyone a...  the boondoggle of Solendra and Obamacare He ne...  days after House Republicans won passage of a ...  and has avoided mention of his Republican succ...  even as President Donald Trump has criticized ...  named for a 1957 Pulitzer Prize-winning book b...  members of Congress                                 former Obama staffers and celebrities includi...
9;MACY’S GETS THE BOOT FROM LOYAL CUSTOMERS AFT... because we ve learned thousands of customers ar... Macy s has received complaints from approximate... 000 customers since ending its relationship wit...  including phone                                    Facebook and email. A Macy s spokesperson woul...   Our Facebook page is often times used by our ... nan                                                nan                                                                                               NaN
15;White House declines to say if Trump has mad... despite reports indicating that he would pull o... Spicer said: “When the president has a decision     he’ll make that announcement and he’ll make it...  Spicer said: “I obviously don’t know whether o...  but when he’s ready to make an announcement        he’ll make it clear.” ;1                          nan                                                nan                                                                                               NaN

In [38]:
df3 = df3[["text", "label"]]

KeyError: "None of [Index(['text', 'label'], dtype='str')] are in the [columns]"

In [39]:
df3 = pd.read_csv(
    "../data/raw/dataset3/train.csv",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

In [40]:
print(df3.columns)

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='str')

In [41]:
df3["text"] = df3["title"].fillna('') + " " + df3["text"].fillna('')

In [42]:
df3 = df3[["text", "label"]]

In [43]:
df3["label"].value_counts()

label
1    13246
0    11107
Name: count, dtype: int64

In [44]:
df3.dropna(inplace=True)

df3.drop_duplicates(subset=["text"], inplace=True)

df3 = df3.sample(frac=1, random_state=42)

In [45]:
pf_fake = pd.read_csv(
    "../data/raw/fakenewsnet/PolitiFact_fake_news_content.csv"
)

pf_real = pd.read_csv(
    "../data/raw/fakenewsnet/PolitiFact_real_news_content.csv"
)

In [46]:
print(pf_fake.columns)

Index(['id', 'title', 'text', 'url', 'top_img', 'authors', 'source',
       'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'],
      dtype='str')

In [47]:
pf_fake["text"] = (
    pf_fake["title"].fillna('') + " " +
    pf_fake["text"].fillna('')
)

pf_real["text"] = (
    pf_real["title"].fillna('') + " " +
    pf_real["text"].fillna('')
)

In [48]:
pf_fake["label"] = 1
pf_real["label"] = 0

In [49]:
pf_fake = pf_fake[["text", "label"]]

pf_real = pf_real[["text", "label"]]

In [50]:
politifact_df = pd.concat([pf_fake, pf_real])

In [51]:
politifact_df.dropna(inplace=True)

politifact_df.drop_duplicates(subset=["text"], inplace=True)

politifact_df = politifact_df.sample(frac=1, random_state=42)

In [52]:
df1 = pd.concat([df1, politifact_df])

In [53]:
liar_train = pd.read_csv(
    "../data/raw/liar/train.tsv",
    sep="\t",
    header=None
)

liar_test = pd.read_csv(
    "../data/raw/liar/test.tsv",
    sep="\t",
    header=None
)

liar_valid = pd.read_csv(
    "../data/raw/liar/valid.tsv",
    sep="\t",
    header=None
)

In [54]:
columns = [
    "id",
    "label",
    "statement",
    "subject",
    "speaker",
    "speaker_job",
    "state_info",
    "party_affiliation",
    "barely_true_counts",
    "false_counts",
    "half_true_counts",
    "mostly_true_counts",
    "pants_on_fire_counts",
    "context"
]

liar_train.columns = columns
liar_test.columns = columns
liar_valid.columns = columns

In [55]:
liar = pd.concat([
    liar_train,
    liar_test,
    liar_valid
])

In [56]:
liar = liar[["statement", "label"]]

In [57]:
liar.rename(columns={
    "statement": "text"
}, inplace=True)

In [58]:
label_map = {
    "true": 0,
    "mostly-true": 0,
    "half-true": 0,
    "false": 1,
    "pants-fire": 1,
    "barely-true": 1
}

liar["label"] = liar["label"].map(label_map)

In [59]:
liar.dropna(inplace=True)

liar.drop_duplicates(subset=["text"], inplace=True)

liar = liar.sample(frac=1, random_state=42)

In [60]:
df3_train = pd.read_csv(
    "../data/raw/dataset3/train.csv",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

df3_test = pd.read_csv(
    "../data/raw/dataset3/test.csv",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

df3_eval = pd.read_csv(
    "../data/raw/dataset3/evaluation.csv",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

In [61]:
print(df3_train.columns)

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='str')

In [62]:
for df in [df3_train, df3_test, df3_eval]:

    df["text"] = (
        df["title"].fillna('') + " " +
        df["text"].fillna('')
    )

In [63]:
df3_train = df3_train[["text", "label"]]

df3_test = df3_test[["text", "label"]]

df3_eval = df3_eval[["text", "label"]]

In [64]:
df3_train = df3_train[["text", "label"]]

df3_test = df3_test[["text", "label"]]

df3_eval = df3_eval[["text", "label"]]

In [65]:
df3 = pd.concat([
    df3_train,
    df3_test,
    df3_eval
])

In [66]:
df3.dropna(inplace=True)

df3.drop_duplicates(subset=["text"], inplace=True)

df3 = df3.sample(frac=1, random_state=42)

In [67]:
final_df = pd.concat([
    df1,
    liar,
    df3
])

In [68]:
final_df.dropna(inplace=True)

In [69]:
final_df.drop_duplicates(subset=["text"], inplace=True)

In [70]:
final_df = final_df.sample(frac=1, random_state=42)

In [71]:
import re

def clean_text(text):

    text = str(text).lower()

    # remove urls
    text = re.sub(r"http\S+", "", text)

    # remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [72]:
final_df["text"] = final_df["text"].apply(clean_text)

In [73]:
final_df = final_df[
    final_df["text"].str.strip() != ""
]

In [74]:
final_df.head()

                                                    text  label
10188  us to search russian consulate in san francisc...      1
4351   turkey seizes largest ever haul of ancient sta...      1
5339   breaking hr mcmaster explains why washington p...      0
9685   seventyfour percent of rhode islanders support...      0
6537   adidas flawlessly trolls antigay bigots who sl...      0

In [75]:
final_df["label"].value_counts()

label
1    27764
0    25871
Name: count, dtype: int64

In [76]:
final_df.shape

(53635, 2)

In [77]:
final_df.to_csv(
    "../data/processed/final_cleaned_dataset.csv",
    index=False
)